package com.hcl.challenge;

import java.util.ArrayList;
import java.util.Scanner;

/**
 * @author Gangareddy
 * 
 * 
 */
public class Employee
{
	static void printData(ArrayList<EmployeePojo> dataList)
	{// Print the data
		for (EmployeePojo datalst : dataList)
		{
			System.out.print("Id :" + datalst.getId() + "\n");

			System.out.print("Name :" + datalst.getName() + "\n");

			System.out.print("Address :" + datalst.getAddress() + "\n");

			System.out.print("Phone Number :" + datalst.getPhone() + "\n");

		}

	}

	public static void main(String args[])
	{
		Scanner scanner = new Scanner(System.in);
		System.out.println("Total No of People : ");
		int totalCount = Integer.parseInt(scanner.nextLine());

		ArrayList<EmployeePojo> dataList = new ArrayList<EmployeePojo>();
		// Read all the data from User
		for (int i = 0; i < totalCount; i++)
		{
			EmployeePojo bean = new EmployeePojo();
			// id can also be autogenerated based on value of i
			System.out.print("Id :");
			bean.setId(scanner.nextInt());

			// Get the user's Name.
			System.out.print("Name :");
			bean.setName(scanner.next());

			// Get the user's address.
			System.out.print("Address :");
			bean.setAddress(scanner.next());

			// Get the user's phone number.
			System.out.print("Phone Number :");
			bean.setPhone(scanner.next());
			dataList.add(bean);
		}
		printData(dataList);

	}
}



